### ISSUE TITLE
EOF Error

### ISSUE THREAD

**Issue by dominiciun** [FarisHijazi/deblack#6]
```

Press [q] to stop, [?] for help
[vost#0:0/libx264 @ 0000015df9583440] Could not open encoder before EOF
[aost#0:1/aac @ 0000015df9449d40] Could not open encoder before EOF
[aost#0:1/aac @ 0000015df9449d40] Task finished with error code: -22 (Invalid argument)
[vost#0:0/libx264 @ 0000015df9583440] Task finished with error code: -22 (Invalid argument)
[aost#0:1/aac @ 0000015df9449d40] Terminating thread with return code -22 (Invalid argument)
[vost#0:0/libx264 @ 0000015df9583440] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 0000015df9439700] Nothing was written into output file, because at least one of its streams received no packets.
```

**Comment by FarisHijazi** [comment]
likely an error with ffmpeg itself, or the video is corrupted

run something like ffmpeg -i video.mp4 and see what happens

closing for now

**Comment by dominiciun** [comment]
The video is not corrupted and is playable.

Somehow there seems to be a problem that prevents deblack from deblacking on non-Linux based oses.

The same video is deblack-able on a Linux environment but fails in a Windows environment.

This likely has to do with the entire/parts of `filter_complex` string is improperly escaped in Windows. Since the ffprobe command works but the following ffmpeg command from the ffprobe debug runs with an error.

**Comment by CracklySilver** [comment]
Ever found a workaround for windows? I'm getting no error, but also no output, the code runs fine, but it appears like the output file isn't being saved

**Comment by FarisHijazi** [comment]
you're right about the escaping, that's a good point
I will likely not fix this as I don't have time, but you could use something like git-bash or WSL in windows as a workaround
